### ISSUE TITLE
deploy fast api server

### ISSUE THREAD

**Issue by yishain11** [Makes-Innovation-Hub/code-genie-server#9]
🧱 blocked by: #8 #7 
DOD:

- [x]  using render, deploy fastapi repo - dev branch. this will be our dev server env.
- [x]  go over the deployment logs and make sure that it works. fix any erros you find.
- [x]  save url inside a env variable
- [x]  specify the env var name and its usage inside your readme file
- [x]  test that the deployment works with curl
- [x]  add unit test that send a req to the server location to make sure that it works.

**Comment by MohamadShaheen** [comment]
[FastAPI Server](https://code-genie-server.onrender.com)
